version: '3'
services:
  orchestrator-web:
    build: .
    container_name: orchestrator-web
    hostname: orchestrator-web-host
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://localhost:6379/0
      - OLLAMA_URL=${OLLAMA_URL}
    depends_on:
      - my-redis

  orchestrator-worker:
    build: .
    command: celery -A celery_app worker
    container_name: orchestrator-worker
    hostname: orchestrator-worker-host
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://localhost:6379/0
      - ORCHESTRATOR_WEB_URL=http://orchestrator-web:5000
      - OLLAMA_URL=${OLLAMA_URL}
    depends_on:
      - my-redis

  my-redis:
    image: redis:latest
    container_name: my-redis
    hostname: my-redis-host
    ports:
      - "6379:6379"
